services:
  zookeeper:
    image: bitnami/zookeeper:3.9.2-debian-12-r11
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  nagios_simulator:
    build: ./nagios_simulator
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      - kafka

  rca_consumer:
    build: ./rca_consumer
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "5000:5000"
    depends_on:
      - kafka
